using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LibraryDV.Models;

namespace LibraryDV.Repos
{
    class AnimalRepo : IAnimalRepo
    {
        private List<Animal> _animals = new List<Animal>();

        //default constructor
        public AnimalRepo() { }

        //find a specific animal by ID
        public Animal GetAnimal()
        {
            return _animals.FirstOrDefault();
        }

        //find all animals
        public List<Animal> GetAllAnimals()
        {
            return _animals;
        }

        //add a new animal object to the list
        public void CreateAnimal(Animal animal)
        {
            _animals.Add(animal);
        }

        //find a specific animal by ID and remove it
        public void DeleteAnimal(int animalID)
        {
            //AUTOGENERATED LOGIC
            var animal = _animals.FirstOrDefault(a => a.ID == animalID);
            if (animal != null)
            {
                _animals.Remove(animal);
            }
        }

        //takes a specific animal object and returns it again after edits have been made
        public Animal EditAnimal(Animal animal)
        {
            //AUTOGENERATED LOGIC
            return _animals.FirstOrDefault(a => a.ID == animal.ID); 
        }


    }
}
