using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LibraryDV.Models;

namespace LibraryDV.Repos
{
    class BookingRepo
    {
        //Lucas Ingvardtsen
        private List<Booking> _bookings = new List<Booking>();

        public BookingRepo() { }

        //find a specific booking
        public Booking GetBooking(int id)
        {
            return _bookings.FirstOrDefault(b => b.BookingID == id);
        }

        //find all bookings
        public List<Booking> GetAllBookings()
        {
            return _bookings;
        }

        //add a new booking object to the list
        public void CreateBooking(Booking booking)
        {
            _bookings.Add(booking);
        }

        //find a specific booking by ID and remove it
        public void DeleteBooking(int bookingID)
        {
            //AUTOGENERATED LOGIC
            var booking = _bookings.FirstOrDefault(a => a.BookingID == bookingID);
            if (booking != null)
            {
                _bookings.Remove(booking);
            }
        }
    }
}
