using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LibraryDV.Models;

namespace LibraryDV.Repos
{
    class BookingRepo
    {
        //Lucas Ingvardtsen
        private List<Booking> _bookings = new List<Booking>();

        public BookingRepo() { }

        //find a specific booking
        public Booking GetBooking()
        {
            return _bookings.FirstOrDefault();
        }

        //find all bookings
        public List<Booking> GetAllBookings()
        {
            return _bookings;
        }

        //add a new booking object to the list
        public void CreateBooking(Booking booking)
        {
            _bookings.Add(booking);
        }

        //find a specific booking by ID and remove it
        public void DeleteBooking(int bookingID)
        {
            //AUTOGENERATED LOGIC
            var booking = _bookings.FirstOrDefault(a => a.BookingID == bookingID);
            if (booking != null)
            {
                _bookings.Remove(booking);
            }
        }

        public override string ToString()
        {
            string list = string.Empty;
            foreach (Booking booking in _bookings)
            {
                list += $"Booking ID: {booking.BookingID}\nDyr: {booking.AnimalID}\nUser: {booking.UserID}\nDato: {booking.Date}\n fra kl: {booking.Hour}\nKommentar: {booking.Comment}";
            }
            return list;
        }
    }
}
